timeout: 4500s

options:

steps:
# Build gce_vm_image_import.
- name: 'google/cloud-sdk:alpine'
  args: ['gcloud', 'workflows', 'execute', 'workflow-build-and-deploy', '--data={}']
  env: ['CGO_ENABLED=0']
#TODO: --data define release phase