timeout: 4500s

options:

steps:
# Pull from main.
- name: 'docker'
  args: ['docker', 'pull', us-east4-docker.pkg.dev/tzz-noogler-3/wrappers/gce_vm_image_import:release]
  env: ['CGO_ENABLED=0']
# Tag with commit SHA & push.
- name: 'docker'
  args: ['docker', 'tag', us-east4-docker.pkg.dev/tzz-noogler-3/wrappers/gce_vm_image_import:release, us-east1-docker.pkg.dev/tzz-noogler-3/wrappers/gce_vm_image_import:$COMMIT_SHA]
  env: ['CGO_ENABLED=0']
- name: 'docker'
  args: ['docker', 'push', us-east1-docker.pkg.dev/tzz-noogler-3/wrappers/gce_vm_image_import:$COMMIT_SHA]
  env: ['CGO_ENABLED=0']
# Tag with 'release' & push
- name: 'docker'
  args: ['docker', 'tag', us-east4-docker.pkg.dev/tzz-noogler-3/wrappers/gce_vm_image_import:release, us-east1-docker.pkg.dev/tzz-noogler-3/wrappers/gce_vm_image_import:release]
  env: ['CGO_ENABLED=0']
- name: 'docker'
  args: ['docker', 'push', us-east1-docker.pkg.dev/tzz-noogler-3/wrappers/gce_vm_image_import:release]
  env: ['CGO_ENABLED=0']
