timeout: 4500s

options:
  env:
  - GO111MODULE=auto
  - GOPROXY=https://proxy.golang.org
  volumes:
  - name: go-pkg
    path: /go/pkg
  - name: go-src
    path: /go/src

substitutions:
  _RELEASE: 'latest'

steps:
# Build gce_vm_image_import.
- name: 'golang'
  dir: 'cli_tools/gce_vm_image_import'
  args: ['go', 'build', '-o=/workspace/linux/gce_vm_image_import']
  env: ['CGO_ENABLED=0']
- name: 'gcr.io/kaniko-project/executor:v1.1.0'
  args:
  - --destination=us-east1-docker.pkg.dev/$PROJECT_ID/wrappers/gce_vm_image_import:$_RELEASE
  - --destination=us-east1-docker.pkg.dev/$PROJECT_ID/wrappers/gce_vm_image_import:$COMMIT_SHA
  - --destination=us-east4-docker.pkg.dev/$PROJECT_ID/wrappers/gce_vm_image_import:$_RELEASE
  - --destination=us-east4-docker.pkg.dev/$PROJECT_ID/wrappers/gce_vm_image_import:$COMMIT_SHA
  - --context=/workspace
  - --dockerfile=gce_vm_image_import.Dockerfile

# Build gce_onestep_image_import.
- name: 'golang'
  dir: 'cli_tools/gce_onestep_image_import'
  args: ['go', 'build', '-o=/workspace/linux/gce_onestep_image_import']
  env: ['CGO_ENABLED=0']
- name: 'gcr.io/kaniko-project/executor:v1.1.0'
  args:
  - --destination=us-east1-docker.pkg.dev/$PROJECT_ID/wrappers/gce_onestep_image_import:$_RELEASE
  - --destination=us-east1-docker.pkg.dev/$PROJECT_ID/wrappers/gce_onestep_image_import:$COMMIT_SHA
  - --destination=us-east4-docker.pkg.dev/$PROJECT_ID/wrappers/gce_onestep_image_import:$_RELEASE
  - --destination=us-east4-docker.pkg.dev/$PROJECT_ID/wrappers/gce_onestep_image_import:$COMMIT_SHA
  - --context=/workspace
  - --dockerfile=gce_onestep_image_import.Dockerfile

# Build gce_vm_image_export.
- name: 'golang'
  dir: 'cli_tools/gce_vm_image_export'
  args: ['go', 'build', '-o=/workspace/linux/gce_vm_image_export']
  env: ['CGO_ENABLED=0']
- name: 'gcr.io/kaniko-project/executor:v1.1.0'
  args:
  - --destination=us-east1-docker.pkg.dev/$PROJECT_ID/wrappers/gce_vm_image_export:$_RELEASE
  - --destination=us-east1-docker.pkg.dev/$PROJECT_ID/wrappers/gce_vm_image_export:$COMMIT_SHA
  - --destination=us-east4-docker.pkg.dev/$PROJECT_ID/wrappers/gce_vm_image_export:$_RELEASE
  - --destination=us-east4-docker.pkg.dev/$PROJECT_ID/wrappers/gce_vm_image_export:$COMMIT_SHA
  - --context=/workspace
  - --dockerfile=gce_vm_image_export.Dockerfile

# Build gce_ovf_import.
- name: 'golang'
  dir: 'cli_tools/gce_ovf_import'
  args: ['go', 'build', '-o=/workspace/linux/gce_ovf_import']
  env: ['CGO_ENABLED=0']
- name: 'gcr.io/kaniko-project/executor:v1.1.0'
  args:
  - --destination=us-east1-docker.pkg.dev/$PROJECT_ID/wrappers/gce_ovf_import:$_RELEASE
  - --destination=us-east1-docker.pkg.dev/$PROJECT_ID/wrappers/gce_ovf_import:$COMMIT_SHA
  - --destination=us-east4-docker.pkg.dev/$PROJECT_ID/wrappers/gce_ovf_import:$_RELEASE
  - --destination=us-east4-docker.pkg.dev/$PROJECT_ID/wrappers/gce_ovf_import:$COMMIT_SHA
  - --context=/workspace
  - --dockerfile=gce_ovf_import.Dockerfile

# Build gce_ovf_export.
- name: 'golang'
  dir: 'cli_tools/gce_ovf_export'
  args: ['go', 'build', '-o=/workspace/linux/gce_ovf_export']
  env: ['CGO_ENABLED=0']
- name: 'gcr.io/kaniko-project/executor:v1.1.0'
  args:
  - --destination=us-east1-docker.pkg.dev/$PROJECT_ID/wrappers/gce_ovf_export:$_RELEASE
  - --destination=us-east1-docker.pkg.dev/$PROJECT_ID/wrappers/gce_ovf_export:$COMMIT_SHA
  - --destination=us-east4-docker.pkg.dev/$PROJECT_ID/wrappers/gce_ovf_export:$_RELEASE
  - --destination=us-east4-docker.pkg.dev/$PROJECT_ID/wrappers/gce_ovf_export:$COMMIT_SHA
  - --context=/workspace
  - --dockerfile=gce_ovf_export.Dockerfile

# Build gce_windows_upgrade.
- name: 'golang'
  dir: 'cli_tools/gce_windows_upgrade'
  args: ['go', 'build', '-o=/workspace/linux/gce_windows_upgrade']
  env: ['CGO_ENABLED=0']
- name: 'gcr.io/kaniko-project/executor:v1.1.0'
  args:
  - --destination=us-east1-docker.pkg.dev/$PROJECT_ID/wrappers/gce_windows_upgrade:$_RELEASE
  - --destination=us-east1-docker.pkg.dev/$PROJECT_ID/wrappers/gce_windows_upgrade:$COMMIT_SHA
  - --destination=us-east4-docker.pkg.dev/$PROJECT_ID/wrappers/gce_windows_upgrade:$_RELEASE
  - --destination=us-east4-docker.pkg.dev/$PROJECT_ID/wrappers/gce_windows_upgrade:$COMMIT_SHA
  - --context=/workspace
  - --dockerfile=gce_windows_upgrade.Dockerfile
