timeout: 4500s

options:
  env:
  - GO111MODULE=auto
  - GOPROXY=https://proxy.golang.org
  volumes:
  - name: go-pkg
    path: /go/pkg
  - name: go-src
    path: /go/src

substitutions:
  _RELEASE: 'latest'

steps:
# Build gce_vm_image_import.
- name: 'gcloud'
  args: ['gcloud', 'workflows', 'execute', 'workflows-1', '--data={}']
  env: ['CGO_ENABLED=0']
